services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"           # Host 9090 -> Container 8080
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8080             # <-- match Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]

  db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
