services: 
  backend:
    build: .
    ports:
      - '9500:9500'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
